# Generated by Django 5.0.3 on 2024-05-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nv', models.IntegerField()),
                ('ho_ten', models.CharField(max_length=200)),
                ('luong_cb', models.IntegerField()),
                ('so_gio_lam', models.FloatField()),
                ('so_sp', models.IntegerField()),
                ('he_so_cv', models.FloatField()),
                ('thuong', models.FloatField()),
                ('luong_ht', models.FloatField()),
            ],
        ),
    ]
