# Generated by Django 5.0.3 on 2024-05-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='he_so_cv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='so_gio_lam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='so_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='thuong',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
