# Generated by Django 5.0.3 on 2024-05-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_nhanvien_he_so_cv_alter_nhanvien_so_gio_lam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='loai_nv',
            field=models.CharField(default='van_phong', max_length=100),
        ),
    ]
