# Generated by Django 5.0.3 on 2024-05-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_nhanvien_he_so_cv_alter_nhanvien_so_gio_lam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='luong_ht',
            field=models.FloatField(null=True),
        ),
    ]
